SECTION_HEADINGS = {
    "project_overview": {"zh-CN": "项目概述", "en-US": "Project Overview"},
    "team_intro": {"zh-CN": "团队介绍", "en-US": "Team Introduction"},
    "pain_point_analysis": {"zh-CN": "痛点与需求分析", "en-US": "Pain Point Analysis"},
    "product_service": {"zh-CN": "产品与服务", "en-US": "Product and Service"},
    "technology_innovation": {"zh-CN": "技术/创新点", "en-US": "Technology and Innovation"},
    "market_analysis": {"zh-CN": "市场分析", "en-US": "Market Analysis"},
    "competitor_analysis": {"zh-CN": "竞品分析", "en-US": "Competitor Analysis"},
    "business_model": {"zh-CN": "商业模式", "en-US": "Business Model"},
    "marketing_strategy": {"zh-CN": "营销策略", "en-US": "Marketing Strategy"},
    "operation_plan": {"zh-CN": "运营计划", "en-US": "Operation Plan"},
    "financial_forecast": {"zh-CN": "财务分析", "en-US": "Financial Analysis"},
    "funding_plan": {"zh-CN": "融资计划", "en-US": "Funding Plan"},
    "risk_analysis": {"zh-CN": "风险分析", "en-US": "Risk Analysis"},
    "social_value": {"zh-CN": "社会价值", "en-US": "Social Value"},
    "development_plan": {"zh-CN": "发展规划", "en-US": "Development Plan"},
    "appendix": {"zh-CN": "附录", "en-US": "Appendix"},
    "references": {"zh-CN": "参考资料", "en-US": "References"},
    "swot_analysis": {"zh-CN": "SWOT分析", "en-US": "SWOT Analysis"},
    "pest_analysis": {"zh-CN": "PEST分析", "en-US": "PEST Analysis"},
    "porter_five_forces": {"zh-CN": "波特五力分析", "en-US": "Porter Five Forces"},
    "business_model_canvas": {"zh-CN": "商业模式画布", "en-US": "Business Model Canvas"},
    "tam_sam_som": {"zh-CN": "市场容量测算", "en-US": "TAM SAM SOM"},
    "risk_matrix": {"zh-CN": "风险矩阵", "en-US": "Risk Matrix"},
    "competitor_matrix": {"zh-CN": "竞品矩阵", "en-US": "Competitor Matrix"},
    "growth_strategy": {"zh-CN": "增长策略", "en-US": "Growth Strategy"},
    "funding_suggestion": {"zh-CN": "融资建议", "en-US": "Funding Suggestion"},
    "operations_plan": {"zh-CN": "运营计划", "en-US": "Operations Plan"},
    "financial_analysis": {"zh-CN": "财务分析", "en-US": "Financial Analysis"},
    "development_roadmap": {"zh-CN": "发展路线图", "en-US": "Development Roadmap"},
}

TEMPLATE_PRESETS = {
    "challenge_cup": [
        "project_overview",
        "pain_point_analysis",
        "product_service",
        "technology_innovation",
        "market_analysis",
        "tam_sam_som",
        "competitor_analysis",
        "business_model",
        "marketing_strategy",
        "operation_plan",
        "financial_forecast",
        "funding_plan",
        "risk_analysis",
        "social_value",
        "development_plan",
        "team_intro",
        "references",
        "appendix",
    ],
    "internet_plus": [
        "project_overview",
        "pain_point_analysis",
        "product_service",
        "technology_innovation",
        "market_analysis",
        "tam_sam_som",
        "competitor_analysis",
        "business_model",
        "marketing_strategy",
        "operation_plan",
        "financial_forecast",
        "funding_plan",
        "team_intro",
        "social_value",
        "development_plan",
        "risk_analysis",
        "references",
        "appendix",
    ],
    "generic_startup": [
        "project_overview",
        "pain_point_analysis",
        "product_service",
        "market_analysis",
        "tam_sam_som",
        "competitor_analysis",
        "business_model",
        "marketing_strategy",
        "operation_plan",
        "financial_forecast",
        "funding_plan",
        "risk_analysis",
        "social_value",
        "development_plan",
        "references",
        "appendix",
    ],
}

FINAL_BP_SECTION_ORDER = [
    "project_overview",
    "pain_point_analysis",
    "product_service",
    "market_analysis",
    "tam_sam_som",
    "competitor_analysis",
    "business_model",
    "marketing_strategy",
    "operation_plan",
    "financial_forecast",
    "funding_plan",
    "risk_analysis",
    "social_value",
    "development_plan",
    "references",
    "appendix",
]

SUPPORTED_LANGUAGES = {"zh-CN", "en-US"}
SUPPORTED_TEMPLATE_TYPES = {"generic_startup", "challenge_cup", "internet_plus", "custom"}
SUPPORTED_SECTION_KEYS = set(SECTION_HEADINGS.keys())
